service: thorus-api

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  apiKeys:
    - prodKey
    - ${self:provider.stage}-prodKey
    - ${file(./config.json):apiKey} #Clients connecting to this Rest API will then need to set any of these API keys values in the x-api-key header of their request.
  runtime: nodejs6.10
  stage: prod
  region: ${file(./config.json):region}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:PutItem
      Resource: ${file(./config.json):dynamoResource}

functions:
  createThread:
    handler: handler.createThread
    events:
      - http:
          path: thorus/create/thread
          method: post
          cors: true
          private: true
  getAllThreads:
    handler: handler.getAllThreads
    events:
      - http:
          path: thorus/read/{days}
          method: get
          request:
            parameters:
              paths:
                days: true
          cors: true
          private: true
  createPost:
    handler: handler.createPost
    events:
      - http:
          path: thorus/create/{thread}
          method: post
          request:
            parameters:
              paths:
                thread: true
          cors: true
          private: true