service: thorus-api

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ${file(./config.json):region}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:PutItem
      Resource: ${file(./config.json):dynamoResource}

functions:
  createThread:
    handler: ./endpoints/createThread.main
    events:
      - http:
          path: thorus/create/thread
          method: post
          cors: true
          authorizer: aws_iam
  getAllThreads:
    handler: ./endpoints/getAllThreads.main
    events:
      - http:
          path: thorus/read/all
          method: get
          cors: true
          authorizer: aws_iam